/* Generated by wayland-scanner 1.22.0 */

#ifndef WINEHUA_TOPLEVEL_SERVER_PROTOCOL_H
#define WINEHUA_TOPLEVEL_SERVER_PROTOCOL_H

#include <stdint.h>
#include <stddef.h>
#include "wayland-server.h"

#ifdef  __cplusplus
extern "C" {
#endif

struct wl_client;
struct wl_resource;

/**
 * @page page_winehua_toplevel The winehua_toplevel protocol
 * @section page_ifaces_winehua_toplevel Interfaces
 * - @subpage page_iface_winehua_toplevel - WineHua toplevel mobile attributes
 */
struct winehua_toplevel;
struct wl_surface;

#ifndef WINEHUA_TOPLEVEL_INTERFACE
#define WINEHUA_TOPLEVEL_INTERFACE
/**
 * @page page_iface_winehua_toplevel winehua_toplevel
 * @section page_iface_winehua_toplevel_desc Description
 *
 * Vendor protocol between Wine's wayland driver and the WineHua compositor.
 *
 * Base xdg-shell cannot express Win32 modal dialog relations (an owned
 * popup whose owner is disabled), so Wine reports them here; the
 * compositor uses the relation to keep the dialog above its owner and to
 * block input routed to a disabled owner window.
 * @section page_iface_winehua_toplevel_api API
 * See @ref iface_winehua_toplevel.
 */
/**
 * @defgroup iface_winehua_toplevel The winehua_toplevel interface
 *
 * Vendor protocol between Wine's wayland driver and the WineHua compositor.
 *
 * Base xdg-shell cannot express Win32 modal dialog relations (an owned
 * popup whose owner is disabled), so Wine reports them here; the
 * compositor uses the relation to keep the dialog above its owner and to
 * block input routed to a disabled owner window.
 */
extern const struct wl_interface winehua_toplevel_interface;
#endif

/**
 * @ingroup iface_winehua_toplevel
 * @struct winehua_toplevel_interface
 */
struct winehua_toplevel_interface {
	/**
	 * Set or clear the modal relation of a toplevel
	 *
	 * surface: the dialog toplevel; owner_surface: its owner
	 * toplevel (NULL when clearing); modal: 1 = apply, 0 = release.
	 */
	void (*set_modal)(struct wl_client *client,
			  struct wl_resource *resource,
			  struct wl_resource *surface,
			  struct wl_resource *owner_surface,
			  uint32_t modal);
};


/**
 * @ingroup iface_winehua_toplevel
 */
#define WINEHUA_TOPLEVEL_SET_MODAL_SINCE_VERSION 1

#ifdef  __cplusplus
}
#endif

#endif
