/* Generated by wayland-scanner 1.22.0 */

#include <stdlib.h>
#include <stdint.h>
#include "wayland-util.h"

#ifndef __has_attribute
# define __has_attribute(x) 0  /* Compatibility with non-clang compilers. */
#endif

#if (__has_attribute(visibility) || defined(__GNUC__) && __GNUC__ >= 4)
#define WL_PRIVATE __attribute__ ((visibility("hidden")))
#else
#define WL_PRIVATE
#endif

extern const struct wl_interface wl_surface_interface;

static const struct wl_interface *winehua_toplevel_types[] = {
	&wl_surface_interface,
	&wl_surface_interface,
	NULL,
};

static const struct wl_message winehua_toplevel_requests[] = {
	{ "set_modal", "o?ou", winehua_toplevel_types + 0 },
};

WL_PRIVATE const struct wl_interface winehua_toplevel_interface = {
	"winehua_toplevel", 1,
	1, winehua_toplevel_requests,
	0, NULL,
};

