#version 450
layout(local_size_x = 9) in;
layout(set = 0, binding = 0) uniform sampler2D sourceImage;
layout(set = 0, binding = 1, std430) buffer Samples { uint pixels[9]; } outputSamples;
layout(push_constant) uniform ImageSize { ivec2 size; } imageSize;

void main()
{
    uint index = gl_LocalInvocationID.x;
    ivec2 coord = ivec2(int(index % 3u) * (imageSize.size.x - 1) / 2,
                        int(index / 3u) * (imageSize.size.y - 1) / 2);
    vec4 color = texelFetch(sourceImage, coord, 0);
    uvec4 channels = uvec4(round(color * 255.0));
    outputSamples.pixels[index] = channels.r | (channels.g << 8u) |
                                   (channels.b << 16u) | (channels.a << 24u);
}
