export const startServer: (sockPath: string) => boolean;
export interface NativePerformanceSnapshot {
  pid: number;
  monotonicAvailable: boolean;
  cpuAvailable: boolean;
  rssAvailable: boolean;
  monotonicNs: number;
  processCpuNs: number;
  rssHighWaterKiB: number;
  clockTicksPerSecond: number;
  directActive: boolean;
  directPresents: number;
  directGamePresents: number;
  eglPresents: number;
  eglGpuPresents: number;
}
export const captureNativePerformance: () => NativePerformanceSnapshot;
export interface PhoneSharedBufferProbeResult {
  gate: string;
  status: string;
  stage: string;
  lastChildStage: string;
  loaderPath: string;
  deviceName: string;
  childStderr: string;
  parentPid: number;
  pid: number;
  forkServerPid: number;
  launchCode: number;
  childExitCode: number;
  childWaitStatus: number;
  childSignal: number;
  childReaped: boolean;
  childExitObserved: boolean;
  localParcelRoundtrip: boolean;
  preserveLowMappings: boolean;
  standardFork: boolean;
  systemStart: boolean;
  guestExport: boolean;
  childImageAllocations: number;
  childNativeBufferExports: number;
  childRealReleaseFenceImports: number;
  childRealRenderFenceExports: number;
  hostRealRenderFenceImports: number;
  hostRealReleaseFenceExports: number;
  childKilledByProbe: boolean;
  childDeviceCreated: boolean;
  vkResult: number;
  systemError: number;
  parentFdBefore: number;
  parentFdAfter: number;
  backingFds: number;
  originalFieldCount: number;
  framesVerified: number;
  childImageImports: number;
  childReleaseFenceImports: number;
  childRenderFenceExports: number;
  hostImageImports: number;
  hostImageReuses: number;
  hostRenderFenceImports: number;
  hostReleaseFenceExports: number;
  diagnosticCpuReadBytes: number;
  imageCpuReadBytes: number;
  imageCpuUploadBytes: number;
  imageGpuCopyCount: number;
}
export const runPhoneSharedBufferProbe: (preserveLowMappings?: boolean, standardFork?: boolean,
  systemStart?: boolean, guestExport?: boolean) => Promise<PhoneSharedBufferProbeResult>;
export interface ExternalImageProbeResult {
  handleType: number;
  format: number;
  tiling: number;
  usage: number;
  result: number;
  features: number;
  compatibleHandleTypes: number;
  exportFromImportedHandleTypes: number;
}
export interface DirectVulkanProbeResult {
  gate: string;
  status: string;
  launchMode: string;
  stage: string;
  pid: number;
  callbackStatus: number;
  parentFdCount: number;
  parentRssKiB: number;
  ncpStatus: number;
  vkResult: number;
  loaderVersion: number;
  requestedApiVersion: number;
  instanceExtensionCount: number;
  deviceExtensionCount: number;
  nativeCapabilities: number;
  externalImages: ExternalImageProbeResult[];
  opaqueFdBufferQueried: boolean;
  opaqueFdBufferFeatures: number;
  apiVersion: number;
  icdEnvironment: string;
  pixelCheck: boolean;
  elapsedMs: number;
  loaderPath: string;
  deviceName: string;
}
export const runDirectVulkanProbe: (earlyPhoneFork?: boolean) => Promise<DirectVulkanProbeResult>;
export const runDirectVulkanInlineProbe: () => Promise<DirectVulkanProbeResult>;
export const preparePhoneDirectForkServer: () => number;
export const runDirectVulkanForkServerProbe: () => Promise<DirectVulkanProbeResult>;
export const runDirectVulkanCreateProbe: () => Promise<DirectVulkanProbeResult>;
export const runDirectVulkanSystemCreateProbe: () => Promise<DirectVulkanProbeResult>;
export interface DirectWineIpcProbeResult {
  gate: string;
  status: string;
  stage: string;
  pid: number;
  replyPid: number;
  fdCount: number;
  launchCode: number;
  callbackCode: number;
  ipcCode: number;
  parentFdsOpen: number;
  deathReceived: number;
  registryExited: number;
}
export const runDirectWineIpcProbe: () => Promise<DirectWineIpcProbeResult>;
export const runDirectWineBrokerIpcProbe: () => Promise<DirectWineIpcProbeResult>;
export interface DirectWineSurfaceIpcProbeResult {
  gate: string;
  status: string;
  stage: string;
  pid: number;
  launchCode: number;
  firstAttach: number;
  directRoute: number;
  firstQuery: number;
  staleRejected: number;
  staleAttachAccepted: number;
  firstQueryAfterStale: number;
  resized: number;
  oldGenerationRejected: number;
  detach: number;
  detachedQueryRejected: number;
  deathReceived: number;
}
export const runDirectWineSurfaceIpcProbe: () => Promise<DirectWineSurfaceIpcProbeResult>;
export interface DirectSurfaceProbeResult {
  gate: string;
  status: string;
  stage: string;
  pid: number;
  framesPassed: number;
  width: number;
  height: number;
  queueSize: number;
  lastBufferSeq: number;
  launchCode: number;
  callbackCode: number;
  killCode: number;
  abortMode: boolean;
  parentFdCount: number;
  parentRssKiB: number;
  pixelCheck: boolean;
  importCheck: boolean;
  importCount: number;
  reuseCount: number;
  importVkResult: number;
}
export const runDirectSurfaceProbe: () => Promise<DirectSurfaceProbeResult>;
export const runDirectSurfaceAbortProbe: () => Promise<DirectSurfaceProbeResult>;
export const runDirectGpuSurfaceProbe: () => Promise<DirectSurfaceProbeResult>;
export const runDirectGpuImportProbe: () => Promise<DirectSurfaceProbeResult>;
export const setHostShadowProfile: (profile: string) => boolean;
export const launchClient: (exePath: string, argv: string[], sockPath: string, libPath: string,
  homeDir: string, d3dBackend?: string, dxvkBackend?: string, wineLang?: string,
  containerId?: string, directNcpSession?: boolean, desktopVulkanCompositor?: boolean,
  desktopStallSeconds?: number) => number;
export const stopClient: () => void;
export const stopAll: () => void;
export const setStateCallback: (cb: (state: string) => void) => void;
export const setToplevelCallback: (cb: (id: number, event: string, data: string) => void) => void;
export const setImeCallback: (cb: (active: number, x: number, y: number, w: number, h: number) => void) => void;
export const registerHostWindow: (windowId: number) => void;
export const dumpWindowLayout: (displayId?: number) => void;
export const setPointerLockCallback: (cb: (locked: boolean, toplevelId: number) => void) => void;
export const sendImeCommit: (text: string) => void;
export const sendImePreedit: (text: string, start: number, end: number) => void;
export const imeBackspace: () => void;
export const setPendingToplevel: (id: number) => void;
export const cancelPendingToplevel: (id: number) => void;
export const getCurrentToplevelId: () => number;
export const destroyToplevel: (id: number) => void;
export const sendToplevelClose: (id: number) => void;
export const runWineExe: (binDir: string, sockPath: string, libPath: string, exePath: string, homeDir: string) => void;
export interface WineProgramOptions {
  windowsExePath: string;
  argv: string[];
  environment: Record<string, string>;
  workingDirectory: string;
  containerId?: string;
  d3dBackend: string;
  dxvkBackend?: string;
  presentBackend: string;
}
export interface WineProcessHandle {
  found: boolean;
  pid: number;
  status: string;
  startTimestamp: number;
  endTimestamp: number;
  exitCode: number | null;
  exitCodeSource: string;
}
export const runWineProgram: (options: WineProgramOptions) => WineProcessHandle;
export const queryWineProcess: (pid: number) => WineProcessHandle;
export const terminateWineProcess: (pid: number) => boolean;
export const checkWinePrefix: (containerId?: string) => boolean;
export const resetWinePrefix: (containerId?: string) => boolean;
export const setOutputSize: (w: number, h: number) => void;
export const setDisplayScale: (scale: number) => void;
export const setDesktopMode: (enabled: boolean) => void;
export const setPhoneMode: (enabled: boolean) => void;
export const findToplevelAt: (px: number, py: number) => number;
export const raiseToplevel: (toplevelId: number) => void;
export const createRenderer: (toplevelId: number, surfaceId: BigInt) => void;
export const resizeRenderer: (toplevelId: number, width: number, height: number) => void;
export const destroyRenderer: (toplevelId: number) => void;
export const sendPointerEvent: (toplevelId: number, action: number, px: number, py: number, button: number, rawDeltaX?: number, rawDeltaY?: number, fromMouse?: boolean) => void;
export const sendKeyEvent: (toplevelId: number, evdevCode: number, pressed: boolean) => void;
export const sendScrollEvent: (toplevelId: number, axis: number, value: number, scrollStep: number, px: number, py: number) => void;
export const notifyToplevelResize: (toplevelId: number, w: number, h: number, resizing?: boolean) => void;
export const notifyToplevelResizeEnd: (toplevelId: number) => void;
export const setToplevelVisible: (toplevelId: number, visible: boolean) => void;
export const getProcessList: () => Array<{pid: number, name: string, path: string, state: string, desktopShell: boolean}>;
export const killProcess: (pid: number) => boolean;
export const termRun: (cols: number, rows: number, cb: (data: ArrayBuffer) => void, onExit: () => void) => number;
export const termSend: (data: ArrayBuffer) => void;
export const termResize: (cols: number, rows: number) => void;
export const termClose: () => void;
