#!/usr/bin/env python3
"""Embed the D2 Vulkan composite shaders as SPIR-V C++ arrays."""

from pathlib import Path
import struct
import subprocess
import tempfile


root = Path(__file__).resolve().parents[1]
shader_dir = root / "entry/src/main/cpp/direct"
with tempfile.TemporaryDirectory() as directory:
    arrays = []
    for stage, symbol in (("vert", "kDirectCompositeVertSpv"),
                          ("frag", "kDirectCompositeFragSpv")):
        source = shader_dir / f"direct_composite.{stage}"
        binary = Path(directory) / f"direct_composite.{stage}.spv"
        subprocess.run(["glslangValidator", "-V", "-S", stage, "-o", str(binary),
                        str(source)], check=True)
        data = binary.read_bytes()
        words = struct.unpack(f"<{len(data) // 4}I", data)
        lines = [f"constexpr uint32_t {symbol}[] = {{"]
        for offset in range(0, len(words), 8):
            lines.append("    " + ", ".join(f"0x{word:08x}" for word in words[offset:offset + 8]) + ",")
        lines.append("};")
        arrays.extend(lines)

header = shader_dir / "direct_composite_spv.h"
header.write_text("\n".join([
    "// Generated by scripts/generate_direct_composite_shader.py.",
    "#pragma once", "#include <cstdint>", "namespace winehua::direct {",
    *arrays, "} // namespace winehua::direct", "",
]), encoding="utf-8")
