#!/usr/bin/env python3
"""Regenerate the Vulkan desktop fragment shader with glslangValidator."""
import pathlib
import struct
import subprocess
import tempfile

root = pathlib.Path(__file__).resolve().parents[1]
directory = root / "entry/src/main/cpp/direct"
with tempfile.TemporaryDirectory(prefix="winehua-desktop-shader-") as temporary:
    output = pathlib.Path(temporary) / "desktop.spv"
    subprocess.run(["glslangValidator", "-V", "--target-env", "vulkan1.1", "-o", str(output),
                    str(directory / "direct_desktop.frag")], check=True)
    data = output.read_bytes()
words = struct.unpack(f"<{len(data) // 4}I", data)
lines = ["#pragma once", "#include <cstdint>", "// Generated by scripts/generate_direct_desktop_shader.py.",
         "static constexpr uint32_t kDirectDesktopFragSpv[] = {"]
for offset in range(0, len(words), 8):
    lines.append("    " + ", ".join(f"0x{word:08x}" for word in words[offset:offset + 8]) + ",")
lines.append("};")
(directory / "direct_desktop_spv.h").write_text("\n".join(lines) + "\n", encoding="utf-8")
